<?php

return [
	'name' => 'KalipsoX',
	'description' => '{"tr":"Bu bir site a&ccedil;\u0131klamas\u0131.","en":"It&#039;s a site description.dfdsf"}',
	'contact_email' => 'halillusion@gmail.com',
	'separator' => '—',
	'language' => 'tr',
	'default_user_role' => 1,
	'log' => true,
	'maintenance_mode' => true,
	'maintenance_mode_desc' => '{"tr":"Bak\u0131m modunday\u0131z.","en":"We are under maintenance."}',
	'mail_send_type' => 'server',
	'smtp_address' => 'smtp.yandex.com.tr',
	'smtp_port' => 587,
	'smtp_email_address' => 'hi@example.com',
	'smtp_email_password' => 'password',
	'smtp_secure' => 'tls',
	'view_cache' => false,
	'db_cache' => true,
	'route_cache' => false,
	'registration_system' => true,
	'last_updated_at' => 1655275294,
	'last_updated_by' => 1,
];
