<?php

/**
 *  KalipsoX - Localization File
 *  English(en)
 **/

return [
    'lang' => [
        'code' => 'en',
        'iso_code' => 'en_US',
        'dir' => 'ltr',
        'timezone' => 'America/New_York',
        'currency' => 'usd',
        'plural_suffix' => 's',
    ],
    'langs' => [
        'tr' => 'Turkish',
        'en' => 'English',
    ],
    'error' => [
        'bad_request' => 'Bad Request!',
        'bad_request_sub_text' => 'This page could not process your request.',
        'unauthorized' => 'Unauthorized!',
        'unauthorized_sub_text' => 'You do not have permission to access this page.',
        'forbidden' => 'Forbidden!',
        'forbidden_sub_text' => 'You do not have permission to access this page.',
        'not_found' => 'Not found!',
        'not_found_sub_text' => 'The page you are looking for was not found.',
        'method_not_allowed' => 'Method not allowed!',
        'method_not_allowed_sub_text' => 'This page does not have permission for the method you requested.',
        'too_many_requests' => 'Too many requests!',
        'too_many_requests_sub_text' => 'You have made too many requests to this page. <br> Please wait:',
        'internal_server_error' => 'Internal Server Error!',
        'internal_server_error_sub_text' => 'This page could not process your request.',
        'service_unavailable' => 'Service Unavailable!',
        'service_unavailable_sub_text' => 'This page is currently unavailable.',
    ],
    'auth' => [
        'login' => 'Login',
        'login_desc' => 'Login to your account',
        'register' => 'Register',
        'register_desc' => 'Create a new account',
        'recovery' => 'Recovery Account',
        'recovery_desc' => 'After entering your e-mail address, you can recover your account by clicking the link sent to you.',
        'recovery_password_desc' => 'You can recover your account by entering your new password below.',
        'email_or_username' => 'E-mail or Username',
        'password' => 'Password',
        'show_password' => 'Show Password',
        'remember_me' => 'Remember Me',
        'recovery_account' => 'Recovery Account',
        'dont_have_account_yet' => 'Don\'t have an account yet?',
        'you_have_already_account' => 'Already have an account?',
        'username' => 'Username',
        'email' => 'E-mail',
        'username_already_exists' => 'This username already exists.',
        'email_already_exists' => 'This e-mail already exists.',
        'register_success' => 'Registration successful. Redirecting to the login page...',
        'registration_system_disabled' => 'User registration system is currently disabled. Please try again later.',
        'verify_account' => 'Verify Account',
        'verify_account_desc' => 'Please verify your account by clicking the button in the e-mail sent to your e-mail address.',
        'your_account_deleted' => 'Sorry, your account has been deleted.',
        'password_incorrect' => 'The password you entered is incorrect.',
        'account_not_found' => 'Account not found. Please check your information and try again.',
        'login_success' => 'Login successful, redirecting...',
        'account_verified' => 'Your account has been verified. Your account is now active.',
        'a_problem_has_occurred' => 'A problem has occurred!',
        'account_updated' => 'Your account has been successfully updated.',
        'account_already_verified' => 'Your account has already been verified.',
        'token_not_found' => 'Invalid or expired token.',
        'recovery_email_sent' => 'A recovery link has been sent to your e-mail address.',
        'new_password' => 'New Password',
        'new_password_confirmation' => 'New Password (Again)',
        'password_changed' => 'Your password has been successfully changed. Redirecting to the login page...',
        'account' => 'Account',
        'account_desc' => 'Welcome to your account page, you can manage your account here.',
        'logout' => 'Logout',
        'sessions' => 'Sessions',
        'sessions_desc' => 'You can manage your sessions from here.',
        'first_name' => 'First Name',
        'last_name' => 'Last Name',
        'email_change_info' => 'After changing your e-mail address, a verification link will be sent to you again.',
        'birthdate' => 'Birthdate',
        'password_change_desc' => 'You can change your password anytime.',
        'set_new_password' => 'Set New Password',
    ],
    'form' => [
        'fill_all_fields' => 'Please fill in all fields.',
        'required_validation' => 'This field is required.',
        'min_validation' => 'This field must be at least :min characters.',
        'max_validation' => 'This field must be at most :max characters.',
        'email_validation' => 'This field must be a valid e-mail address.',
        'url_validation' => 'This field must be a valid URL.',
        'ip_validation' => 'This field must be a valid IP address.',
        'numeric_validation' => 'This field must be numeric.',
        'alpha_validation' => 'This field must be alphabetic.',
        'alphanumeric_validation' => 'This field must be alphanumeric.',
        'regex_validation' => 'This field must be valid.',
        'match_validation' => 'This field must match with :match.',
        'in_validation' => 'This field must be in :in.',
        'not_in_validation' => 'This field must not be in :not_in.',
    ],
    'notification' => [
        'welcome_title' => 'Welcome to Our Community!',
        'welcome_body' => 'Welcome to our community. We are happy to see you here.',
        'welcome_email_title' => 'Your Account is Ready!',
        'welcome_email_body' => 'Hello @:user. <br> We are happy to see you here. <br> Please verify your account by clicking the button below. <br> <a href=":link_url">:link_text</a>',
        'account_verified_title' => 'Your Account is Verified!',
        'account_verified_body' => 'Your account has been verified. You can now use your account.',
        'account_verified_email_title' => 'Your Account is Verified!',
        'account_verified_email_body' => 'Hello @:user. <br> Your account has been verified. You can now use your account. <br> <a href=":link_url">:link_text</a>',
        'recovery_request_title' => 'Account Recovery Request!',
        'recovery_request_body' => 'A password reset request has been created for your account!',
        'recovery_request_email_title' => 'Account Recovery!',
        'recovery_request_email_body' => 'Hello @:user. <br> A password reset request has been created for your account. You can reset your password by clicking the button below. <br> <a href=":link_url">:link_text</a>',
        'recover_success_title' => 'Account Recovery Successful!',
        'recover_success_body' => 'You have successfully recovered your account. You can now use your account.',
        'recover_success_email_title' => 'Account Recovery Successful!',
        'recover_success_email_body' => 'Hello @:user. <br> You have successfully recovered your account. You can now use your account. <br> <a href=":link_url">:link_text</a>',
        'email_change_title' => 'E-mail Change Request!',
        'email_change_body' => 'A e-mail change request has been created for your account!',
        'email_change_email_title' => 'E-mail Change!',
        'email_change_email_body' => 'Hello @:user. <br> A e-mail change request has been created for your account. You can change your e-mail by clicking the button below. <br> <a href=":link_url">:link_text</a>',
    ],
    'base' => [
        'toggle_theme' => 'Toggle Theme',
        'copyright' => 'Copyright',
        'home' => 'Home',
        'back_to_home' => 'Back to Home',
        'sorry' => 'Sorry...',
        'reset' => 'Reset',
        'show_notifications' => 'Show Notifications',
        'latest_notifications' => 'Latest Notifications',
        'notifications' => 'Notifications',
        'notifications_desc' => 'Welcome to the notifications page, you can view your notifications here.',
        'settings' => 'Settings',
        'system_settings' => 'System Settings',
        'dashboard' => 'Dashboard',
        'dashboard_desc' => 'Welcome to your dashboard, you can view a summary of system statistics here.',
        'users' => 'Users',
        'users_desc' => 'Welcome to the users page, you can manage users here.',
        'user_roles' => 'User Roles',
        'user_roles_desc' => 'Welcome to the user roles page, you can manage user roles here.',
        'save' => 'Save',
        'language' => 'Language',
        'nothing_changed' => 'Nothing changed.',
        'see_all' => 'See All',
        'no_notifications' => 'You have no notifications yet.',
    ],
];
