<?php

/**
 *  KalipsoX - Localization File
 *  English(en)
 **/

return [
    'lang' => [
        'code' => 'en',
        'iso_code' => 'en_US',
        'dir' => 'ltr',
        'timezone' => 'America/New_York',
        'currency' => 'usd',
        'plural_suffix' => 's',
    ],
    'langs' => [
        'tr' => 'Turkish',
        'en' => 'English',
    ],
    'error' => [
        'bad_request' => 'Bad Request!',
        'bad_request_sub_text' => 'This page could not process your request.',
        'unauthorized' => 'Unauthorized!',
        'unauthorized_sub_text' => 'You do not have permission to access this page.',
        'forbidden' => 'Forbidden!',
        'forbidden_sub_text' => 'You do not have permission to access this page.',
        'not_found' => 'Not found!',
        'not_found_sub_text' => 'The page you are looking for was not found.',
        'method_not_allowed' => 'Method not allowed!',
        'method_not_allowed_sub_text' => 'This page does not have permission for the method you requested.',
        'too_many_requests' => 'Too many requests!',
        'too_many_requests_sub_text' => 'You have made too many requests to this page. <br> Please wait:',
        'internal_server_error' => 'Internal Server Error!',
        'internal_server_error_sub_text' => 'This page could not process your request.',
        'service_unavailable' => 'Service Unavailable!',
        'service_unavailable_sub_text' => 'This page is currently unavailable.',
    ],
    'auth' => [
        'login' => 'Login',
        'login_desc' => 'Login to your account',
        'register' => 'Register',
        'register_desc' => 'Create a new account',
        'recovery' => 'Recovery Account',
        'recovery_desc' => 'Recover your account',
        'email_or_username' => 'E-mail or Username',
        'password' => 'Password',
        'show_password' => 'Show Password',
        'remember_me' => 'Remember Me',
        'recovery_account' => 'Recovery Account',
        'dont_have_account_yet' => 'Don\'t have an account yet?',
        'you_have_already_account' => 'Already have an account?',
        'username' => 'Username',
        'email' => 'E-mail',
        'username_already_exists' => 'This username already exists.',
        'email_already_exists' => 'This e-mail already exists.',
        'register_success' => 'Registration successful. Redirecting to the login page...',
        'registration_system_disabled' => 'User registration system is currently disabled. Please try again later.',
        'verify_account' => 'Verify Account',
    ],
    'form' => [
        'fill_all_fields' => 'Please fill in all fields.',
        'required_validation' => 'This field is required.',
        'min_validation' => 'This field must be at least :min characters.',
        'max_validation' => 'This field must be at most :max characters.',
        'email_validation' => 'This field must be a valid e-mail address.',
        'url_validation' => 'This field must be a valid URL.',
        'ip_validation' => 'This field must be a valid IP address.',
        'numeric_validation' => 'This field must be numeric.',
        'alpha_validation' => 'This field must be alphabetic.',
        'alphanumeric_validation' => 'This field must be alphanumeric.',
        'regex_validation' => 'This field must be valid.',
        'match_validation' => 'This field must match with :match.',
        'in_validation' => 'This field must be in :in.',
        'not_in_validation' => 'This field must not be in :not_in.',
    ],
    'notification' => [
        'welcome_title' => 'Welcome to Our Community!',
        'welcome_body' => 'Welcome to our community. We are happy to see you here.',
        'welcome_email_title' => 'Your Account is Ready!',
        'welcome_email_body' => 'Hello :user. <br> We are happy to see you here. <br> Please verify your account by clicking the button below. <br> <a href=":link_url">:link_text</a>',
    ],
    'base' => [
        'toggle_theme' => 'Toggle Theme',
        'copyright' => 'Copyright',
        'home' => 'Home',
        'back_to_home' => 'Back to Home',
        'sorry' => 'Sorry...',
    ],
];
