<?php

/**
 *  KalipsoX - Localization File
 *  Turkish(tr)
 **/

return [
    'lang' => [
        'code' => 'tr',
        'iso_code' => 'tr_TR',
        'dir' => 'ltr',
        'timezone' => 'Europe/Istanbul',
        'currency' => 'try',
        'plural_suffix' => '',
    ],
    'langs' => [
        'tr' => 'Türkçe',
        'en' => 'İngilizce',
    ],
    'error' => [
        'bad_request' => 'Hatalı İstek!',
        'bad_request_sub_text' => 'Bu sayfa isteğinizi işleyemedi.',
        'unauthorized' => 'Yetkisiz!',
        'unauthorized_sub_text' => 'Bu sayfaya erişim izniniz yok.',
        'forbidden' => 'Yasaklandı!',
        'forbidden_sub_text' => 'Bu sayfaya erişim izniniz yok.',
        'not_found' => 'Bulunamadı!',
        'not_found_sub_text' => 'Aradığınız sayfa bulunamadı.',
        'method_not_allowed' => 'Methoda izin verilmez!',
        'method_not_allowed_sub_text' => 'Bu sayfa istekte bulunduğunuz method için izne sahip değil.',
        'too_many_requests' => 'Çok fazla istek!',
        'too_many_requests_sub_text' => 'Bu sayfaya çok fazla istekte bulundunuz. <br> Lütfen bekleyin:',
        'internal_server_error' => 'Sunucu Hatası!',
        'internal_server_error_sub_text' => 'Bu sayfa isteğinizi işleyemedi.',
        'service_unavailable' => 'Servis Kullanılamaz!',
        'service_unavailable_sub_text' => 'Bu sayfa şu anda kullanılamıyor.',
    ],
    'auth' => [
        'login' => 'Giriş Yap',
        'login_desc' => 'Hesabınıza giriş yapın',
        'register' => 'Kayıt Ol',
        'register_desc' => 'Yeni bir hesap oluşturun',
        'recovery' => 'Hesabı Kurtar',
        'recovery_desc' => 'Hesabınızı kurtarın',
        'email_or_username' => 'E-posta veya Kullanıcı Adı',
        'password' => 'Şifre',
        'show_password' => 'Şifreyi Göster',
        'remember_me' => 'Beni Hatırla',
        'recovery_account' => 'Hesabı Kurtar',
        'dont_have_account_yet' => 'Henüz bir hesabınız yok mu?',
        'you_have_already_account' => 'Zaten bir hesabınız var mı?',
        'username' => 'Kullanıcı Adı',
        'email' => 'E-posta',
        'username_already_exists' => 'Bu kullanıcı adı zaten mevcut.',
        'email_already_exists' => 'Bu e-posta adresi zaten mevcut.',
        'register_success' => 'Kayıt işlemi başarılı. Giriş sayfasına yönlendiriliyorsunuz...',
        'registration_system_disabled' => 'Kullanıcı kayıt sistemi şu anda devre dışı bırakılmıştır. Lütfen daha sonra tekrar deneyin.',
        'verify_account' => 'Hesabı Doğrula',
    ],
    'form' => [
        'fill_all_fields' => 'Lütfen tüm alanları doldurunuz.',
        'required_validation' => 'Bu alan zorunludur.',
        'min_validation' => 'Bu alan en az :min karakter olmalıdır.',
        'max_validation' => 'Bu alan en fazla :max karakter olmalıdır.',
        'email_validation' => 'Lütfen geçerli bir e-posta adresi giriniz.',
        'url_validation' => 'Lütfen geçerli bir URL adresi giriniz.',
        'ip_validation' => 'Lütfen geçerli bir IP adresi giriniz.',
        'numeric_validation' => 'Lütfen sadece sayısal değerler giriniz.',
        'alpha_validation' => 'Lütfen sadece harf değerleri giriniz.',
        'alphanumeric_validation' => 'Lütfen sadece harf ve sayısal değerler giriniz.',
        'regex_validation' => 'Lütfen geçerli bir değer giriniz.',
        'match_validation' => 'Bu alanın değeri :match değeri ile eşleşmelidir.',
        'in_validation' => 'Girdiğiniz değer :in içerisinde olmalıdır.',
        'not_in_validation' => 'Girdiğiniz değer :not_in içerisinde olmamalıdır.',
    ],
    'notification' => [
        'welcome_title' => 'Aramıza Hoş Geldin!',
        'welcome_body' => 'Şimdi hesabını kullanmaya başlayabilirsin.',
        'welcome_email_title' => 'Hesabın Başarıyla Oluşturuldu!',
        'welcome_email_body' => 'Merhaba :user, <br> Hesabın başarıyla oluşturuldu. Aşağıdaki bağlantı ile hesabını doğrulayabilirsin. <br> <a href=":link_url">:link_text</a>',
    ],
    'base' => [
        'toggle_theme' => 'Renk Modunu Değiştir',
        'copyright' => 'Telif Hakkı',
        'home' => 'Anasayfa',
        'back_to_home' => 'Ana Sayfaya Dön',
        'sorry' => 'Üzgünüz...',
    ],
];
